info:
  contact: {}
  description: Go 语言编程之旅：一起用 Go 做项目
  license: {}
  termsOfService: https://github.com/go-programming-tour-book
  title: 博客系统
  version: "1.0"
paths:
  /tags:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200": {}
      summary: ping example
      tags:
      - example
swagger: "2.0"
